In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import torch
import pandas as pd

from sklearn.metrics import classification_report, roc_curve, auc, roc_auc_score, accuracy_score, precision_recall_fscore_support, confusion_matrix

# Sent140

In [2]:
test = torch.load("../data/sent140-test.pth") # TensorDataset: (input_ids, attention_mask, labels)
test_dl = torch.utils.data.DataLoader(test, batch_size=32)
# labels = test.tensors[2].numpy()
# labels[:5]

In [3]:
all_labels = []
for _, _, labels in test_dl:
    all_labels.extend([*labels])
labels = np.array(all_labels)
labels[:5]

array([1, 0, 0, 1, 0])

In [4]:
probs = np.load("sent140-probs-new-1.npy")
probs[:5]

array([[-0.03856618, -0.03297899],
       [-0.03856619, -0.03297899],
       [-0.03856618, -0.03297899],
       [-0.03856618, -0.03297899],
       [-0.03856619, -0.03297899]], dtype=float32)

In [5]:
preds = np.argmax(probs, axis=1)
preds[:5]

array([1, 1, 1, 1, 1])

In [8]:
set(preds)

{1}

In [6]:
labels.shape, preds.shape

((320000,), (320000,))

In [7]:
accuracy = accuracy_score(labels, preds)
print(f"accuracy: {accuracy}")
precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='binary')
print(f"precision: {precision}")
print(f"recall: {recall}")
print(f"f1: {f1}")
conf_mat = confusion_matrix(labels, preds)
print(f"confusion matrix:\n{conf_mat}")

accuracy: 0.500796875
precision: 0.500796875
recall: 1.0
f1: 0.6673746238977211
confusion matrix:
[[     0 159745]
 [     0 160255]]


In [ ]:
from sklearn.metrics import (hamming_loss, accuracy_score, jaccard_score,
                             precision_score, recall_score, f1_score,
                             roc_auc_score, average_precision_score, 
                             classification_report)

print("Classification Report:\n")
print(classification_report(labels, preds, target_names=emotion_labels))

In [ ]:
exact_match_accuracy = accuracy_score(labels, preds)
print(f"Exact Match Accuracy: {exact_match_accuracy:.4f}")

averagePrecision = average_precision_score(labels, probs, average='macro')
print(f"Average Precision: {averagePrecision:.4f}")

In [ ]:
hammingLoss = hamming_loss(labels, preds)
print("Hamming Loss: {:.4f}".format(hammingLoss))

exactMatchRatio = accuracy_score(labels, preds)
print("Exact Match Ratio: {:.4f}".format(exactMatchRatio))

jaccardSimilarity = jaccard_score(labels, preds, average='samples')
print("Jaccard Similarity: {:.4f}\n".format(jaccardSimilarity))

In [ ]:
print(f"{'Emotion':<20} {'ROC-AUC':<10} {'PR-AUC':<10}")
print("-" * 40)

for i, label in enumerate(emotion_labels):
    roc_auc = roc_auc_score(labels[:, i], probs[:, i])
    pr_auc = average_precision_score(labels[:, i], probs[:, i])
    print(f"{label:<20} {roc_auc:.4f}     {pr_auc:.4f}")